//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.296
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClingClient.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClingClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   123과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ABC {
            get {
                return ResourceManager.GetString("ABC", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap bg_inputbox_26_l {
            get {
                object obj = ResourceManager.GetObject("bg_inputbox_26_l", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap bg_inputbox_26_m {
            get {
                object obj = ResourceManager.GetObject("bg_inputbox_26_m", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap bg_inputbox_26_r {
            get {
                object obj = ResourceManager.GetObject("bg_inputbox_26_r", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap bg_listbar_bot_l {
            get {
                object obj = ResourceManager.GetObject("bg_listbar_bot_l", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap bg_listbar_bot_m {
            get {
                object obj = ResourceManager.GetObject("bg_listbar_bot_m", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap bg_listbar_bot_r {
            get {
                object obj = ResourceManager.GetObject("bg_listbar_bot_r", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap bg_listbar_mid_l {
            get {
                object obj = ResourceManager.GetObject("bg_listbar_mid_l", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap bg_listbar_mid_m {
            get {
                object obj = ResourceManager.GetObject("bg_listbar_mid_m", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap bg_listbar_mid_r {
            get {
                object obj = ResourceManager.GetObject("bg_listbar_mid_r", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap bg_listbar_top_l {
            get {
                object obj = ResourceManager.GetObject("bg_listbar_top_l", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap bg_listbar_top_m {
            get {
                object obj = ResourceManager.GetObject("bg_listbar_top_m", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap bg_listbar_top_r {
            get {
                object obj = ResourceManager.GetObject("bg_listbar_top_r", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap bg_mid_l {
            get {
                object obj = ResourceManager.GetObject("bg_mid_l", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap bg_mid_m {
            get {
                object obj = ResourceManager.GetObject("bg_mid_m", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap bg_mid_r {
            get {
                object obj = ResourceManager.GetObject("bg_mid_r", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap bg_popup_bot_l {
            get {
                object obj = ResourceManager.GetObject("bg_popup_bot_l", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap bg_popup_bot_m {
            get {
                object obj = ResourceManager.GetObject("bg_popup_bot_m", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap bg_popup_bot_r {
            get {
                object obj = ResourceManager.GetObject("bg_popup_bot_r", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap bg_popup_mid_l {
            get {
                object obj = ResourceManager.GetObject("bg_popup_mid_l", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap bg_popup_mid_m {
            get {
                object obj = ResourceManager.GetObject("bg_popup_mid_m", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap bg_popup_mid_r {
            get {
                object obj = ResourceManager.GetObject("bg_popup_mid_r", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap bg_popup_notit_l {
            get {
                object obj = ResourceManager.GetObject("bg_popup_notit_l", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap bg_popup_notit_m {
            get {
                object obj = ResourceManager.GetObject("bg_popup_notit_m", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap bg_popup_notit_r {
            get {
                object obj = ResourceManager.GetObject("bg_popup_notit_r", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap bg_update_progress {
            get {
                object obj = ResourceManager.GetObject("bg_update_progress", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_apptop_close02_hover {
            get {
                object obj = ResourceManager.GetObject("btn_apptop_close02_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_apptop_close02_normal {
            get {
                object obj = ResourceManager.GetObject("btn_apptop_close02_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_apptop_close02_press {
            get {
                object obj = ResourceManager.GetObject("btn_apptop_close02_press", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_apptop_min_hover {
            get {
                object obj = ResourceManager.GetObject("btn_apptop_min_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_apptop_min_normal {
            get {
                object obj = ResourceManager.GetObject("btn_apptop_min_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_apptop_min_press {
            get {
                object obj = ResourceManager.GetObject("btn_apptop_min_press", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_backup_change_normal {
            get {
                object obj = ResourceManager.GetObject("btn_backup_change_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_backup_change_press {
            get {
                object obj = ResourceManager.GetObject("btn_backup_change_press", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_cling_start_disable {
            get {
                object obj = ResourceManager.GetObject("btn_cling_start_disable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_cling_start_normal {
            get {
                object obj = ResourceManager.GetObject("btn_cling_start_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_cling_start_press {
            get {
                object obj = ResourceManager.GetObject("btn_cling_start_press", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_disk_add_hover {
            get {
                object obj = ResourceManager.GetObject("btn_disk_add_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_disk_add_normal {
            get {
                object obj = ResourceManager.GetObject("btn_disk_add_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_disk_error {
            get {
                object obj = ResourceManager.GetObject("btn_disk_error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_disk_hover {
            get {
                object obj = ResourceManager.GetObject("btn_disk_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_disk_normal {
            get {
                object obj = ResourceManager.GetObject("btn_disk_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_list_file_hover {
            get {
                object obj = ResourceManager.GetObject("btn_list_file_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_list_file_normal {
            get {
                object obj = ResourceManager.GetObject("btn_list_file_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_list_file_press {
            get {
                object obj = ResourceManager.GetObject("btn_list_file_press", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_list_more {
            get {
                object obj = ResourceManager.GetObject("btn_list_more", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_logo_cling {
            get {
                object obj = ResourceManager.GetObject("btn_logo_cling", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_next_64_normal {
            get {
                object obj = ResourceManager.GetObject("btn_next_64_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_next_64_press {
            get {
                object obj = ResourceManager.GetObject("btn_next_64_press", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_online_off {
            get {
                object obj = ResourceManager.GetObject("btn_online_off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_online_on {
            get {
                object obj = ResourceManager.GetObject("btn_online_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_popoup_write_normal {
            get {
                object obj = ResourceManager.GetObject("btn_popoup_write_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_popoup_write_press {
            get {
                object obj = ResourceManager.GetObject("btn_popoup_write_press", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_popup_cancel_normal {
            get {
                object obj = ResourceManager.GetObject("btn_popup_cancel_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_popup_cancel_press {
            get {
                object obj = ResourceManager.GetObject("btn_popup_cancel_press", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_popup_close_normal {
            get {
                object obj = ResourceManager.GetObject("btn_popup_close_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_popup_close_press {
            get {
                object obj = ResourceManager.GetObject("btn_popup_close_press", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_popup_enter_disable {
            get {
                object obj = ResourceManager.GetObject("btn_popup_enter_disable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_popup_enter_normal {
            get {
                object obj = ResourceManager.GetObject("btn_popup_enter_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_popup_enter_press {
            get {
                object obj = ResourceManager.GetObject("btn_popup_enter_press", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_popup_ignore_normal {
            get {
                object obj = ResourceManager.GetObject("btn_popup_ignore_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_popup_ignore_press {
            get {
                object obj = ResourceManager.GetObject("btn_popup_ignore_press", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_popup_ok_disable {
            get {
                object obj = ResourceManager.GetObject("btn_popup_ok_disable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_popup_ok_norml {
            get {
                object obj = ResourceManager.GetObject("btn_popup_ok_norml", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_popup_ok_press {
            get {
                object obj = ResourceManager.GetObject("btn_popup_ok_press", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_prev_hover {
            get {
                object obj = ResourceManager.GetObject("btn_prev_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_prev_normal {
            get {
                object obj = ResourceManager.GetObject("btn_prev_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_prev_press {
            get {
                object obj = ResourceManager.GetObject("btn_prev_press", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_ref_hover {
            get {
                object obj = ResourceManager.GetObject("btn_ref_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_ref_normal {
            get {
                object obj = ResourceManager.GetObject("btn_ref_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_ref_press {
            get {
                object obj = ResourceManager.GetObject("btn_ref_press", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_search_hover {
            get {
                object obj = ResourceManager.GetObject("btn_search_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_search_normal {
            get {
                object obj = ResourceManager.GetObject("btn_search_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_search_press {
            get {
                object obj = ResourceManager.GetObject("btn_search_press", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_setting_account_hover {
            get {
                object obj = ResourceManager.GetObject("btn_setting_account_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_setting_account_normal {
            get {
                object obj = ResourceManager.GetObject("btn_setting_account_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_setting_account_press {
            get {
                object obj = ResourceManager.GetObject("btn_setting_account_press", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_setting_logout_hover {
            get {
                object obj = ResourceManager.GetObject("btn_setting_logout_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_setting_logout_normal {
            get {
                object obj = ResourceManager.GetObject("btn_setting_logout_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_setting_logout_press {
            get {
                object obj = ResourceManager.GetObject("btn_setting_logout_press", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_setting_normal {
            get {
                object obj = ResourceManager.GetObject("btn_setting_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_setting_press {
            get {
                object obj = ResourceManager.GetObject("btn_setting_press", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_setting_search_hover {
            get {
                object obj = ResourceManager.GetObject("btn_setting_search_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_setting_search_normal {
            get {
                object obj = ResourceManager.GetObject("btn_setting_search_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_setting_search_press {
            get {
                object obj = ResourceManager.GetObject("btn_setting_search_press", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_sort_left {
            get {
                object obj = ResourceManager.GetObject("btn_sort_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_sort_right {
            get {
                object obj = ResourceManager.GetObject("btn_sort_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_state_record_disable {
            get {
                object obj = ResourceManager.GetObject("btn_state_record_disable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_state_record_off {
            get {
                object obj = ResourceManager.GetObject("btn_state_record_off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_state_record_on {
            get {
                object obj = ResourceManager.GetObject("btn_state_record_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_state_sync_disable {
            get {
                object obj = ResourceManager.GetObject("btn_state_sync_disable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_state_sync_off {
            get {
                object obj = ResourceManager.GetObject("btn_state_sync_off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_state_sync_on {
            get {
                object obj = ResourceManager.GetObject("btn_state_sync_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_tit_edit {
            get {
                object obj = ResourceManager.GetObject("btn_tit_edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_treeview_openh_down {
            get {
                object obj = ResourceManager.GetObject("btn_treeview_openh_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_treeview_openh_hover {
            get {
                object obj = ResourceManager.GetObject("btn_treeview_openh_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_treeview_openh_normal {
            get {
                object obj = ResourceManager.GetObject("btn_treeview_openh_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_update_delay_normal {
            get {
                object obj = ResourceManager.GetObject("btn_update_delay_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_update_delay_press {
            get {
                object obj = ResourceManager.GetObject("btn_update_delay_press", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_update_normal {
            get {
                object obj = ResourceManager.GetObject("btn_update_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_update_press {
            get {
                object obj = ResourceManager.GetObject("btn_update_press", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_write_record_disable {
            get {
                object obj = ResourceManager.GetObject("btn_write_record_disable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_write_record_normal {
            get {
                object obj = ResourceManager.GetObject("btn_write_record_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btn_write_record_press {
            get {
                object obj = ResourceManager.GetObject("btn_write_record_press", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Icon cling {
            get {
                object obj = ResourceManager.GetObject("cling", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Bitmap disk_01_normal {
            get {
                object obj = ResourceManager.GetObject("disk_01_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap disk_02_normal {
            get {
                object obj = ResourceManager.GetObject("disk_02_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap disk_03_normal {
            get {
                object obj = ResourceManager.GetObject("disk_03_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap disk_04_normal {
            get {
                object obj = ResourceManager.GetObject("disk_04_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap disk_05_normal {
            get {
                object obj = ResourceManager.GetObject("disk_05_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap disk_06_normal {
            get {
                object obj = ResourceManager.GetObject("disk_06_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap disk_07_normal {
            get {
                object obj = ResourceManager.GetObject("disk_07_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap disk_08_normal {
            get {
                object obj = ResourceManager.GetObject("disk_08_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap disk_09_normal {
            get {
                object obj = ResourceManager.GetObject("disk_09_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap disk_10_normal {
            get {
                object obj = ResourceManager.GetObject("disk_10_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap div_apptop {
            get {
                object obj = ResourceManager.GetObject("div_apptop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap div_list {
            get {
                object obj = ResourceManager.GetObject("div_list", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap div_login_bot {
            get {
                object obj = ResourceManager.GetObject("div_login_bot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ico_complete {
            get {
                object obj = ResourceManager.GetObject("ico_complete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ico_disk_update {
            get {
                object obj = ResourceManager.GetObject("ico_disk_update", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ico_dot {
            get {
                object obj = ResourceManager.GetObject("ico_dot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ico_error_b {
            get {
                object obj = ResourceManager.GetObject("ico_error_b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ico_file {
            get {
                object obj = ResourceManager.GetObject("ico_file", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ico_folder {
            get {
                object obj = ResourceManager.GetObject("ico_folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ico_online {
            get {
                object obj = ResourceManager.GetObject("ico_online", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ico_popup_info {
            get {
                object obj = ResourceManager.GetObject("ico_popup_info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ico_state_record_disable {
            get {
                object obj = ResourceManager.GetObject("ico_state_record_disable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ico_state_record_off {
            get {
                object obj = ResourceManager.GetObject("ico_state_record_off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ico_state_record_on {
            get {
                object obj = ResourceManager.GetObject("ico_state_record_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ico_state_sync_disable {
            get {
                object obj = ResourceManager.GetObject("ico_state_sync_disable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ico_state_sync_off {
            get {
                object obj = ResourceManager.GetObject("ico_state_sync_off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ico_state_sync_on {
            get {
                object obj = ResourceManager.GetObject("ico_state_sync_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ico_view_off {
            get {
                object obj = ResourceManager.GetObject("ico_view_off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ico_view_on {
            get {
                object obj = ResourceManager.GetObject("ico_view_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ico_warning {
            get {
                object obj = ResourceManager.GetObject("ico_warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_backup_disk {
            get {
                object obj = ResourceManager.GetObject("img_backup_disk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_date_dd_01 {
            get {
                object obj = ResourceManager.GetObject("img_date_dd_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_date_dd_02 {
            get {
                object obj = ResourceManager.GetObject("img_date_dd_02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_date_dd_03 {
            get {
                object obj = ResourceManager.GetObject("img_date_dd_03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_date_dd_04 {
            get {
                object obj = ResourceManager.GetObject("img_date_dd_04", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_date_dd_05 {
            get {
                object obj = ResourceManager.GetObject("img_date_dd_05", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_date_dd_06 {
            get {
                object obj = ResourceManager.GetObject("img_date_dd_06", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_date_dd_07 {
            get {
                object obj = ResourceManager.GetObject("img_date_dd_07", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_date_dd_08 {
            get {
                object obj = ResourceManager.GetObject("img_date_dd_08", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_date_dd_09 {
            get {
                object obj = ResourceManager.GetObject("img_date_dd_09", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_date_dd_10 {
            get {
                object obj = ResourceManager.GetObject("img_date_dd_10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_date_dd_11 {
            get {
                object obj = ResourceManager.GetObject("img_date_dd_11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_date_dd_12 {
            get {
                object obj = ResourceManager.GetObject("img_date_dd_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_date_dd_13 {
            get {
                object obj = ResourceManager.GetObject("img_date_dd_13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_date_dd_14 {
            get {
                object obj = ResourceManager.GetObject("img_date_dd_14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_date_dd_15 {
            get {
                object obj = ResourceManager.GetObject("img_date_dd_15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_date_dd_16 {
            get {
                object obj = ResourceManager.GetObject("img_date_dd_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_date_dd_17 {
            get {
                object obj = ResourceManager.GetObject("img_date_dd_17", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_date_dd_18 {
            get {
                object obj = ResourceManager.GetObject("img_date_dd_18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_date_dd_19 {
            get {
                object obj = ResourceManager.GetObject("img_date_dd_19", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_date_dd_20 {
            get {
                object obj = ResourceManager.GetObject("img_date_dd_20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_date_dd_21 {
            get {
                object obj = ResourceManager.GetObject("img_date_dd_21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_date_dd_22 {
            get {
                object obj = ResourceManager.GetObject("img_date_dd_22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_date_dd_23 {
            get {
                object obj = ResourceManager.GetObject("img_date_dd_23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_date_dd_24 {
            get {
                object obj = ResourceManager.GetObject("img_date_dd_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_date_dd_25 {
            get {
                object obj = ResourceManager.GetObject("img_date_dd_25", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_date_dd_26 {
            get {
                object obj = ResourceManager.GetObject("img_date_dd_26", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_date_dd_27 {
            get {
                object obj = ResourceManager.GetObject("img_date_dd_27", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_date_dd_28 {
            get {
                object obj = ResourceManager.GetObject("img_date_dd_28", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_date_dd_29 {
            get {
                object obj = ResourceManager.GetObject("img_date_dd_29", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_date_dd_30 {
            get {
                object obj = ResourceManager.GetObject("img_date_dd_30", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_date_dd_31 {
            get {
                object obj = ResourceManager.GetObject("img_date_dd_31", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_date_mm_01 {
            get {
                object obj = ResourceManager.GetObject("img_date_mm_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_date_mm_02 {
            get {
                object obj = ResourceManager.GetObject("img_date_mm_02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_date_mm_03 {
            get {
                object obj = ResourceManager.GetObject("img_date_mm_03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_date_mm_04 {
            get {
                object obj = ResourceManager.GetObject("img_date_mm_04", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_date_mm_05 {
            get {
                object obj = ResourceManager.GetObject("img_date_mm_05", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_date_mm_06 {
            get {
                object obj = ResourceManager.GetObject("img_date_mm_06", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_date_mm_07 {
            get {
                object obj = ResourceManager.GetObject("img_date_mm_07", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_date_mm_08 {
            get {
                object obj = ResourceManager.GetObject("img_date_mm_08", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_date_mm_09 {
            get {
                object obj = ResourceManager.GetObject("img_date_mm_09", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_date_mm_10 {
            get {
                object obj = ResourceManager.GetObject("img_date_mm_10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_date_mm_11 {
            get {
                object obj = ResourceManager.GetObject("img_date_mm_11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_date_mm_12 {
            get {
                object obj = ResourceManager.GetObject("img_date_mm_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_info_rewrite {
            get {
                object obj = ResourceManager.GetObject("img_info_rewrite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_list_disk_01 {
            get {
                object obj = ResourceManager.GetObject("img_list_disk_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_list_disk_02 {
            get {
                object obj = ResourceManager.GetObject("img_list_disk_02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_list_disk_03 {
            get {
                object obj = ResourceManager.GetObject("img_list_disk_03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_list_disk_04 {
            get {
                object obj = ResourceManager.GetObject("img_list_disk_04", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_list_disk_05 {
            get {
                object obj = ResourceManager.GetObject("img_list_disk_05", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_list_disk_06 {
            get {
                object obj = ResourceManager.GetObject("img_list_disk_06", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_list_disk_07 {
            get {
                object obj = ResourceManager.GetObject("img_list_disk_07", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_list_disk_08 {
            get {
                object obj = ResourceManager.GetObject("img_list_disk_08", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_list_disk_09 {
            get {
                object obj = ResourceManager.GetObject("img_list_disk_09", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_list_disk_10 {
            get {
                object obj = ResourceManager.GetObject("img_list_disk_10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_list_month {
            get {
                object obj = ResourceManager.GetObject("img_list_month", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_listbar_now {
            get {
                object obj = ResourceManager.GetObject("img_listbar_now", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_login_top {
            get {
                object obj = ResourceManager.GetObject("img_login_top", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_logo_cling {
            get {
                object obj = ResourceManager.GetObject("img_logo_cling", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_scroll_bot {
            get {
                object obj = ResourceManager.GetObject("img_scroll_bot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_scroll_mid {
            get {
                object obj = ResourceManager.GetObject("img_scroll_mid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_scroll_top {
            get {
                object obj = ResourceManager.GetObject("img_scroll_top", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_update_pregress_l {
            get {
                object obj = ResourceManager.GetObject("img_update_pregress_l", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_update_pregress_m {
            get {
                object obj = ResourceManager.GetObject("img_update_pregress_m", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_update_pregress_r {
            get {
                object obj = ResourceManager.GetObject("img_update_pregress_r", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap line_list {
            get {
                object obj = ResourceManager.GetObject("line_list", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap logo_cling {
            get {
                object obj = ResourceManager.GetObject("logo_cling", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap logo_cling_114 {
            get {
                object obj = ResourceManager.GetObject("logo_cling_114", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap logo_cling_54 {
            get {
                object obj = ResourceManager.GetObject("logo_cling_54", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap num_b_bg_center {
            get {
                object obj = ResourceManager.GetObject("num_b_bg_center", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap num_b_bg_left {
            get {
                object obj = ResourceManager.GetObject("num_b_bg_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap num_b_bg_rgt {
            get {
                object obj = ResourceManager.GetObject("num_b_bg_rgt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap num_bar {
            get {
                object obj = ResourceManager.GetObject("num_bar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap tit_num {
            get {
                object obj = ResourceManager.GetObject("tit_num", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap tit_online {
            get {
                object obj = ResourceManager.GetObject("tit_online", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap tutorial_01 {
            get {
                object obj = ResourceManager.GetObject("tutorial_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap tutorial_02 {
            get {
                object obj = ResourceManager.GetObject("tutorial_02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap tutorial_03 {
            get {
                object obj = ResourceManager.GetObject("tutorial_03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap tutorial_04 {
            get {
                object obj = ResourceManager.GetObject("tutorial_04", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap tutorial_05 {
            get {
                object obj = ResourceManager.GetObject("tutorial_05", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap tutorial_arw_left {
            get {
                object obj = ResourceManager.GetObject("tutorial_arw_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap tutorial_arw_left_disable {
            get {
                object obj = ResourceManager.GetObject("tutorial_arw_left_disable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap tutorial_arw_left_ov {
            get {
                object obj = ResourceManager.GetObject("tutorial_arw_left_ov", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap tutorial_arw_rgt {
            get {
                object obj = ResourceManager.GetObject("tutorial_arw_rgt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap tutorial_arw_rgt_disable {
            get {
                object obj = ResourceManager.GetObject("tutorial_arw_rgt_disable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap tutorial_arw_rgt_ov {
            get {
                object obj = ResourceManager.GetObject("tutorial_arw_rgt_ov", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap tutorial_close {
            get {
                object obj = ResourceManager.GetObject("tutorial_close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap tutorial_close_on {
            get {
                object obj = ResourceManager.GetObject("tutorial_close_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap tutorial_x {
            get {
                object obj = ResourceManager.GetObject("tutorial_x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap txt_backup_setspace {
            get {
                object obj = ResourceManager.GetObject("txt_backup_setspace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap txt_copyright {
            get {
                object obj = ResourceManager.GetObject("txt_copyright", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap txt_login_info {
            get {
                object obj = ResourceManager.GetObject("txt_login_info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap txt_login_version {
            get {
                object obj = ResourceManager.GetObject("txt_login_version", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap txt_login_version_0 {
            get {
                object obj = ResourceManager.GetObject("txt_login_version_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap txt_login_version_1 {
            get {
                object obj = ResourceManager.GetObject("txt_login_version_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap txt_login_version_2 {
            get {
                object obj = ResourceManager.GetObject("txt_login_version_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap txt_login_version_3 {
            get {
                object obj = ResourceManager.GetObject("txt_login_version_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap txt_login_version_4 {
            get {
                object obj = ResourceManager.GetObject("txt_login_version_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap txt_login_version_5 {
            get {
                object obj = ResourceManager.GetObject("txt_login_version_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap txt_login_version_6 {
            get {
                object obj = ResourceManager.GetObject("txt_login_version_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap txt_login_version_7 {
            get {
                object obj = ResourceManager.GetObject("txt_login_version_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap txt_login_version_8 {
            get {
                object obj = ResourceManager.GetObject("txt_login_version_8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap txt_login_version_9 {
            get {
                object obj = ResourceManager.GetObject("txt_login_version_9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap txt_login_version_dot {
            get {
                object obj = ResourceManager.GetObject("txt_login_version_dot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap txt_sort_list_disable {
            get {
                object obj = ResourceManager.GetObject("txt_sort_list_disable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap txt_sort_list_on {
            get {
                object obj = ResourceManager.GetObject("txt_sort_list_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap txt_sort_name_on {
            get {
                object obj = ResourceManager.GetObject("txt_sort_name_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap txt_sort_time_on {
            get {
                object obj = ResourceManager.GetObject("txt_sort_time_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap txt_sort_tree_disable {
            get {
                object obj = ResourceManager.GetObject("txt_sort_tree_disable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap txt_sort_tree_on {
            get {
                object obj = ResourceManager.GetObject("txt_sort_tree_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap txt_state_record_disable {
            get {
                object obj = ResourceManager.GetObject("txt_state_record_disable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap txt_state_record_off {
            get {
                object obj = ResourceManager.GetObject("txt_state_record_off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap txt_state_record_on {
            get {
                object obj = ResourceManager.GetObject("txt_state_record_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap txt_state_sync_disable {
            get {
                object obj = ResourceManager.GetObject("txt_state_sync_disable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap txt_state_sync_off {
            get {
                object obj = ResourceManager.GetObject("txt_state_sync_off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap txt_state_sync_on {
            get {
                object obj = ResourceManager.GetObject("txt_state_sync_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap txt_view_all_dimmed {
            get {
                object obj = ResourceManager.GetObject("txt_view_all_dimmed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap txt_view_all_normal {
            get {
                object obj = ResourceManager.GetObject("txt_view_all_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap txt_view_writing_dimmed {
            get {
                object obj = ResourceManager.GetObject("txt_view_writing_dimmed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap txt_view_writing_disable {
            get {
                object obj = ResourceManager.GetObject("txt_view_writing_disable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap txt_view_writing_normal {
            get {
                object obj = ResourceManager.GetObject("txt_view_writing_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
